--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/ItzxDwi/Pathfinder
build-by-default: true
branches:
- V2-PM5
projects:
  libPathfinder:
    path: ""
    model: virion
    type: library
...
